version: "3.9"

services:
  agent-logstash:
    environment:
      - FLEET_ENROLL=1
      - FLEET_INSECURE=true
      - FLEET_URL=https://fleet-server:8220
      - FLEET_ENROLLMENT_TOKEN=c3gxZEhZc0I1aWxkeDFkMWhTVng6VWl0aDE4ejRSMFM1V28xOHhZTG9xUQ==
      - KIBANA_HOST=http://kibana:5601
      - KIBANA_FLEET_USERNAME=elastic
      - KIBANA_FLEET_PASSWORD=elastic
    hostname: agent-logstash
    image: docker.elastic.co/beats/elastic-agent:${STACK_VERSION}
    ports:
      - "9600:9600"
    volumes:
      - certs:/usr/share/certs
    networks:
      - elastic

volumes:
  certs:
    driver: local

networks:
  elastic:
    name: elastic
    driver: bridge
