version: "3.9"

services:
  fleet-server:
    environment:
      - FLEET_SERVER_ENABLE=true
      - FLEET_URL=https://fleet-server:8220
      - FLEET_SERVER_ELASTICSEARCH_HOST=https://es01:9200
      - FLEET_CA=/usr/share/certs/ca/ca.crt
      - FLEET_SERVER_SERVICE_TOKEN=< TOKEN >
      - FLEET_SERVER_POLICY_ID=fleet-server-policy
      - FLEET_SERVER_ELASTICSEARCH_CA=/usr/share/certs/ca/ca.crt
      - CERTIFICATE_AUTHORITIES=/usr/share/certs/ca/ca.crt
      - FLEET_SERVER_CERT=/usr/share/certs/fleet-server/fleet-server.crt
      - FLEET_SERVER_CERT_KEY=/usr/share/certs/fleet-server/fleet-server.key
    image: docker.elastic.co/beats/elastic-agent:${STACK_VERSION}
    hostname: fleet-server
    ports:
      - "8220:8220"
    volumes:
      - certs:/usr/share/certs
    networks:
      - elastic

volumes:
  certs:
    driver: local

networks:
  elastic:
    name: elastic
    driver: bridge
