version: "3.9"

services:
  apm-server:
    image: docker.elastic.co/apm/apm-server:${STACK_VERSION}
    hostname: apm-server
    ports:
      - "8200:8200"
      - "5067:5067"
    volumes:
      - './apm-server/config/apm-server.yml:/usr/share/apm-server/apm-server.yml:ro'
      - certs:/usr/share/apm-server/certs
    user: apm-server
    networks:
      - elastic

volumes:
  certs:
    driver: local

networks:
  elastic:
    name: elastic
    driver: bridge
