version: "3.9"

services:
  agent-apm:
    environment:
      - FLEET_ENROLL=1
      - FLEET_INSECURE=true
      - FLEET_URL=https://fleet-server:8220
      - FLEET_ENROLLMENT_TOKEN=eEtTVlBJc0JNa2tMTkFfcFNsTXQ6ME5OTER5bjBSUC1fRUlKNmxRNk9yQQ==
      - KIBANA_HOST=http://kibana:5601
      - KIBANA_FLEET_USERNAME=elastic
      - KIBANA_FLEET_PASSWORD=elastic
    hostname: agent-apm
    image: docker.elastic.co/beats/elastic-agent:${STACK_VERSION}
    ports:
      - "8201:8200"
    volumes:
      - certs:/usr/share/certs
    networks:
      - elastic

volumes:
  certs:
    driver: local

networks:
  elastic:
    name: elastic
    driver: bridge
