version: "3.9"

services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.8.1
    environment:
      - discovery.type=single-node
      - ES_JAVA_OPTS=-Xms1g -Xmx1g
      - xpack.security.enabled=false
    volumes:
      - es_data:/usr/share/elasticsearch/data
    ports:
      - target: 9200
        published: 9200
    networks:
      - elastic

  kibana:
    image: docker.elastic.co/kibana/kibana:8.8.1
    ports:
      - target: 5601
        published: 5601
    depends_on:
      - elasticsearch
    networks:
      - elastic

  logstash:
    image: docker.elastic.co/logstash/logstash:8.7.1
    ports:
      - '5044:5044'
    volumes:
      - type: bind
        source: ./logstash-pipeline/
        target: /usr/share/logstash/pipeline
        read_only: true
      - type: bind
        source: ./logstash-config/
        target: /usr/share/logstash/config
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
      - xpack.monitoring.enabled=false
    depends_on:
      - elasticsearch
    networks:
      - elastic

  metricbeat:
    image: docker.elastic.co/beats/metricbeat:8.7.1
    environment:
      - setup.kibana.host=kibana:5601
      - output.elasticsearch.hosts=["elasticsearch:9200"]
    depends_on:
      - elasticsearch
    networks:
      - elastic

  filebeat:
    image: docker.elastic.co/beats/filebeat:8.7.1
    volumes:
      - "./filebeat-config/filebeat.yml:/usr/share/filebeat/filebeat.yml:ro"
    environment:
      - setup.kibana.host=kibana:5601
      - output.elasticsearch.hosts=["elasticsearch:9200"]
    depends_on:
      - elasticsearch
    networks:
      - elastic

volumes:
  es_data:
    driver: local

networks:
  elastic:
    name: elastic
    driver: bridge
