version: "3.9"

services:
  agent-filebeat:
    environment:
      - FLEET_ENROLL=1
      - FLEET_INSECURE=true
      - FLEET_URL=https://fleet-server:8220
      - FLEET_ENROLLMENT_TOKEN=Q1Ixd0hZc0I1aWxkeDFkMUoxZHE6Um41bXZTTGRRS2VNQzl6N3BYUldNdw==
      - KIBANA_HOST=http://kibana:5601
      - KIBANA_FLEET_USERNAME=elastic
      - KIBANA_FLEET_PASSWORD=elastic
    hostname: agent-filebeat
    image: docker.elastic.co/beats/elastic-agent:${STACK_VERSION}
    ports:
      - "5066:5066"
    volumes:
      - certs:/usr/share/certs
    networks:
      - elastic

volumes:
  certs:
    driver: local

networks:
  elastic:
    name: elastic
    driver: bridge
