version: "3.9"

services:
  agent-nginx:
    environment:
      - FLEET_ENROLL=1
      - FLEET_INSECURE=true
      - FLEET_URL=https://fleet-server:8220
      - FLEET_ENROLLMENT_TOKEN=SlFnM0dJc0JSM2FXLXREM1Z0WDY6a05fZjZ3Qm5Udi1fVTVpWUM0X2N3Zw==
      - KIBANA_HOST=http://kibana:5601
      - KIBANA_FLEET_USERNAME=elastic
      - KIBANA_FLEET_PASSWORD=elastic
    hostname: agent-nginx
    image: docker.elastic.co/beats/elastic-agent:${STACK_VERSION}
    ports:
      - "1234:80"
    volumes:
      - certs:/usr/share/certs
    networks:
      - elastic

volumes:
  certs:
    driver: local

networks:
  elastic:
    name: elastic
    driver: bridge
