filebeat.config:
  modules:
    path: ${path.config}/modules.d/*.yml
    reload.enabled: true

processors:
  - add_cloud_metadata: ~
  - add_docker_metadata: ~

output.elasticsearch:
  hosts: "https://es01:9200"
  username: "elastic"
  password: "elastic"
  ssl.certificate_authorities: ["/usr/share/filebeat/certs/ca/ca.crt"]
  ssl.certificate: "/usr/share/filebeat/certs/filebeat/filebeat.crt"
  ssl.key: "/usr/share/filebeat/certs/filebeat/filebeat.key"
  ssl.verification_mode: none
  ssl.enabled: true

setup.kibana:
  host: 'kibana:5601'
  username: 'kibana_system'
  password: 'elastic'

#http.enabled: true
#monitoring.enabled: false
xpack.monitoring.enabled: true
