filebeat.config:
  modules:
    path: ${path.config}/modules.d/*.yml
    reload.enabled: true

processors:
  - add_cloud_metadata: ~
  - add_docker_metadata: ~

output.elasticsearch:
  hosts: "https://es01:9200"
  username: "elastic"
  password: "elastic"

setup.kibana:
  host: 'kibana:5601'
  username: 'kibana_system'
  password: 'elastic'

#http.enabled: true
#monitoring.enabled: false