# Module: elasticsearch
# Docs: https://www.elastic.co/guide/en/beats/metricbeat/master/metricbeat-module-elasticsearch.html

- module: elasticsearch
  hosts: ["https://es01:9200"]
  #metricsets:
  #  - node
  #  - node_stats
  period: 10s
  username: "elastic"
  password: "elastic"
  scope: cluster
  xpack.enabled: true
  ssl.enabled: true
  ssl.certificate_authorities: ["/usr/share/metricbeat/certs/ca/ca.crt"]
  ssl.certificate: "/usr/share/metricbeat/certs/metricbeat/metricbeat.crt"
  ssl.key: "/usr/share/metricbeat/certs/metricbeat/metricbeat.key"
  ssl.verification_mode: none
