# Module: kibana
# Docs: https://www.elastic.co/guide/en/beats/metricbeat/master/metricbeat-module-kibana.html

- module: kibana
  hosts: ["kibana:5601"]
  metricsets: ["status"]
  period: 10s
  #basepath: ""
  #username: "user"
  #password: "secret"
  xpack.enabled: true